'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const cordova_data_store_1 = require('./data_store/cordova_data_store');
exports.CordovaDataStore = cordova_data_store_1.default;
const local_data_store_1 = require('./data_store/local_data_store');
exports.LocalDataStore = local_data_store_1.default;
const memory_data_store_1 = require('./data_store/memory_data_store');
exports.MemoryDataStore = memory_data_store_1.default;
const react_data_store_1 = require('./data_store/react_data_store');
exports.ReactDataStore = react_data_store_1.default;
